# Generated by Django 4.2.6 on 2023-10-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('employeeID', models.CharField(max_length=100)),
                ('manager', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
    ]
