# Generated by Django 4.2.6 on 2023-11-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_employeeid_expense_licenseplate_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
