# Generated by Django 4.2.6 on 2023-11-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_expense_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='LicensePlate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='LicensePlate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='media/images/service'),
        ),
    ]
