# Generated by Django 4.2.6 on 2023-11-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_expense_licenseplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='LicensePlate',
            field=models.ForeignKey(blank=True, default='123abc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='LicensePlate',
            field=models.ForeignKey(blank=True, default='123abc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate'),
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateID', models.CharField(max_length=6, default = "123abc")),
    
            ],
        ),
    ]
