# Generated by Django 4.2.6 on 2023-11-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_expense_licenseplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='plateID',
            field=models.CharField(max_length=6),
        ),
    ]
