# Generated by Django 4.2.6 on 2023-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_licenseplate_plateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='plateID',
            field=models.CharField(max_length=6),
        ),
    ]
