# Generated by Django 4.2.6 on 2023-11-25 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_vehicle_currenttrip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripType', models.CharField(choices=[('IN', 'check_in'), ('OUT', 'check_out')], default='OUT', max_length=3)),
                ('location', models.CharField(max_length=32)),
                ('checkout_time', models.DateTimeField(db_comment='Date and time when the Vehicle was checked out')),
                ('checkin_time', models.DateTimeField(db_comment='Date and time when the Vehicle was checked in')),
                ('user', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='currentTrip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.trips'),
        ),
    ]
