# Generated by Django 4.2.6 on 2023-11-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_trip_alter_vehicle_currenttrip_delete_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='licensePlate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tripType',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
