# Generated by Django 4.2.6 on 2023-11-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_trip_licenseplate_alter_trip_triptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='licensePlate',
            field=models.CharField(default='123anc', max_length=6),
        ),
    ]
