# Generated by Django 4.2.6 on 2023-11-26 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_trip_licenseplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='licensePlate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate'),
        ),
    ]
