# Generated by Django 4.2.6 on 2023-11-26 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0015_alter_trip_licenseplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignedEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
