# Generated by Django 4.2.6 on 2023-11-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_ticket_assignedemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='LicensePlate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate'),
        ),
    ]
