# Generated by Django 4.2.6 on 2023-11-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_expense_licenseplate_and_more'),
        ('website', '0017_alter_ticket_licenseplate'),
    ]

    operations = [
    ]
