# Generated by Django 4.2.6 on 2023-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_merge_20231126_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='trip',
            name='checkin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='checkout',
            field=models.DateTimeField(null=True),
        ),
    ]
