# Generated by Django 4.2.6 on 2023-11-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_delete_employeeid_delete_user_alter_trip_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='active',
        ),
    ]
