# Generated by Django 4.2.6 on 2023-11-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_vehicle_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2023-11-28', verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default='2023-11-28', verbose_name='Ticket Date'),
        ),
    ]
