# Generated by Django 4.2.6 on 2023-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_expense_date_alter_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=1984, verbose_name='Expense Date'),
        ),
        
    ]
