# Generated by Django 4.2.7 on 2023-11-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(verbose_name='Ticket Date'),
        ),
    ]
