# Generated by Django 4.2.6 on 2023-12-02 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0022_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(verbose_name='Ticket Date'),
        ),
        migrations.CreateModel(
            name='PersonalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.CharField(max_length=8)),
                ('date', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('reason', models.CharField(max_length=100)),
                ('assignedEmployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
