# Generated by Django 4.2.6 on 2023-12-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_expense_date_alter_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kms',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
