# Generated by Django 4.2.6 on 2023-12-02 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0023_alter_expense_date_alter_ticket_date_personalvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('fault', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Ticket Date')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/ticket')),
                ('LicensePlate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.licenseplate')),
                ('assignedEmployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
