# Generated by Django 4.2.6 on 2023-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assignedEmployee',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kms',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
