# Generated by Django 4.2.6 on 2023-12-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_vehicle_vin_alter_vehicle_kms_and_more'),
        ('website', '0025_alter_vehicle_vin_alter_vehicle_assignedemployee_and_more'),
    ]

    operations = [
    ]
